"""update columns

Revision ID: 3bb96457dc78
Revises: f1f1f3eff880
Create Date: 2025-06-17 10:32:57.803585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb96457dc78'
down_revision = 'f1f1f3eff880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        # Drop existing foreign keys
        batch_op.drop_constraint(batch_op.f('enrollments_student_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('enrollments_course_id_fkey'), type_='foreignkey')

        batch_op.alter_column('student_id',new_column_name='_student_id' , existing_type=sa.Integer())
        batch_op.alter_column('course_id', new_column_name='_course_id', existing_type=sa.Integer())

        batch_op.create_foreign_key(None, 'students', ['_student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'courses', ['_course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        # Drop new foreign key constraints
        batch_op.drop_constraint(batch_op.f('enrollments__student_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('enrollments__course_id_fkey'), type_='foreignkey')

        # Rename columns back
        batch_op.alter_column('_student_id', new_column_name='student_id', existing_type=sa.Integer())
        batch_op.alter_column('_course_id', new_column_name='course_id', existing_type=sa.Integer())

        # Re-create old foreign key constraints
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])